### ISSUE TITLE
flexGrow does not work

### ISSUE THREAD

**Issue by vesparny** [jxnblk/nano-component#2]
Hi,

I tried 

```js
const Wrapper = nano('div')({
  flexGrow: 1,
  display: 'flex'
})
```

this does not work because 1 becomes 1px

The trick to add `px` does not work in every case.

`const px = n => typeof n === 'number' ? n + 'px' : n`

I'd remove this magic and leave the user the responsibility to specify `px` when needed.
Otherwise you'll need to handle all special cases and this would probably make the lib size to grow a lot...tradeoffs :)

Great job BTW, I am already using it on a side project 👍

**Comment by jxnblk** [comment]
Yeah, I should document this. In other libs, I check against a blacklist of non-pixel number CSS properties, but wanted to remove that for this library. The way to handle that with the current API is to pass a string for values like `flexGrow` and `lineHeight`, e.g. `flexGrow: '1'`

**Comment by jxnblk** [comment]
Generally, I find the number to pixel conversion far more useful than having to add a `'px'` string to calculated values

**Comment by vesparny** [comment]
Yes I agree with you. Better to keep this lib as lightweight as possible
